const types = {
  RESET_GAME: "RESET_GAME",
  SET_CANVAS: "SET_CANVAS",
  SET_PLAYER: "SET_PLAYER",
  SET_BULLETS: "SET_BULLETS",
  SET_ASTEROIDS: "SET_ASTEROIDS",
  REMOVE_ASTEROIDS: "REMOVE_ASTEROIDS",
  REMOVE_BULLETS: "REMOVE_BULLETS",
  START_GAME: "START_GAME",
  ADD_POINTS: "ADD_POINTS",
  GET_USERS_SCORES: "GET_USERS_SCORES",
  GET_USERS_SCORES_SUCCESS: "GET_USERS_SCORES_SUCCESS",
  SET_GAME_OVER: "SET_GAME_OVER",
  SET_GAME_OVER_CLICK: "SET_GAME_OVER_CLICK",
};
export default types;
